version: '3.8'

services:
  build_app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: build-container
    image: jestapp:build
    ports:
      - "3000"
  test_app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-container
    image: jestapp:test
    depends_on:
      - build_app
